// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djlwltorcnvwhjumjopt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbHdsdG9yY252d2hqdW1qb3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTY4MzAsImV4cCI6MjA3NDI5MjgzMH0.yn-R-q4yIQHNTLmRME6H6n6MifvMoTiMlpcpr-EZJY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});